import type { Metadata } from "next";
import { pretendard, poppins } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${poppins.variable}`}
    >
      <body>
        <div className="mx-auto w-full max-w-(--max-width) bg-white shadow-2xl min-h-screen px-5 pb-9">
          {children}
        </div>
      </body>
    </html>
  );
}
